/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package dinet.orgsetup62.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Ceg service. Represents a row in the &quot;orgsetup_Ceg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link dinet.orgsetup62.model.impl.CegModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link dinet.orgsetup62.model.impl.CegImpl}.
 * </p>
 *
 * @author gyengelaszlo
 * @see Ceg
 * @see dinet.orgsetup62.model.impl.CegImpl
 * @see dinet.orgsetup62.model.impl.CegModelImpl
 * @generated
 */
public interface CegModel extends BaseModel<Ceg> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ceg model instance should use the {@link Ceg} interface instead.
	 */

	/**
	 * Returns the primary key of this ceg.
	 *
	 * @return the primary key of this ceg
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ceg.
	 *
	 * @param primaryKey the primary key of this ceg
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ceg ID of this ceg.
	 *
	 * @return the ceg ID of this ceg
	 */
	public long getCegId();

	/**
	 * Sets the ceg ID of this ceg.
	 *
	 * @param cegId the ceg ID of this ceg
	 */
	public void setCegId(long cegId);

	/**
	 * Returns the azon_r of this ceg.
	 *
	 * @return the azon_r of this ceg
	 */
	public long getAzon_r();

	/**
	 * Sets the azon_r of this ceg.
	 *
	 * @param azon_r the azon_r of this ceg
	 */
	public void setAzon_r(long azon_r);

	/**
	 * Returns the sub azon_r of this ceg.
	 *
	 * @return the sub azon_r of this ceg
	 */
	public long getSubAzon_r();

	/**
	 * Sets the sub azon_r of this ceg.
	 *
	 * @param subAzon_r the sub azon_r of this ceg
	 */
	public void setSubAzon_r(long subAzon_r);

	/**
	 * Returns the category_r of this ceg.
	 *
	 * @return the category_r of this ceg
	 */
	@AutoEscape
	public String getCategory_r();

	/**
	 * Sets the category_r of this ceg.
	 *
	 * @param category_r the category_r of this ceg
	 */
	public void setCategory_r(String category_r);

	/**
	 * Returns the orgname_r of this ceg.
	 *
	 * @return the orgname_r of this ceg
	 */
	@AutoEscape
	public String getOrgname_r();

	/**
	 * Sets the orgname_r of this ceg.
	 *
	 * @param orgname_r the orgname_r of this ceg
	 */
	public void setOrgname_r(String orgname_r);

	/**
	 * Returns the azon_u of this ceg.
	 *
	 * @return the azon_u of this ceg
	 */
	public long getAzon_u();

	/**
	 * Sets the azon_u of this ceg.
	 *
	 * @param azon_u the azon_u of this ceg
	 */
	public void setAzon_u(long azon_u);

	/**
	 * Returns the sub azon_u of this ceg.
	 *
	 * @return the sub azon_u of this ceg
	 */
	public long getSubAzon_u();

	/**
	 * Sets the sub azon_u of this ceg.
	 *
	 * @param subAzon_u the sub azon_u of this ceg
	 */
	public void setSubAzon_u(long subAzon_u);

	/**
	 * Returns the liferay org ID of this ceg.
	 *
	 * @return the liferay org ID of this ceg
	 */
	public long getLiferayOrgId();

	/**
	 * Sets the liferay org ID of this ceg.
	 *
	 * @param liferayOrgId the liferay org ID of this ceg
	 */
	public void setLiferayOrgId(long liferayOrgId);

	/**
	 * Returns the orgname of this ceg.
	 *
	 * @return the orgname of this ceg
	 */
	@AutoEscape
	public String getOrgname();

	/**
	 * Sets the orgname of this ceg.
	 *
	 * @param orgname the orgname of this ceg
	 */
	public void setOrgname(String orgname);

	/**
	 * Returns the logo of this ceg.
	 *
	 * @return the logo of this ceg
	 */
	@AutoEscape
	public String getLogo();

	/**
	 * Sets the logo of this ceg.
	 *
	 * @param logo the logo of this ceg
	 */
	public void setLogo(String logo);

	/**
	 * Returns the category ID of this ceg.
	 *
	 * @return the category ID of this ceg
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this ceg.
	 *
	 * @param categoryId the category ID of this ceg
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the category of this ceg.
	 *
	 * @return the category of this ceg
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this ceg.
	 *
	 * @param category the category of this ceg
	 */
	public void setCategory(String category);

	/**
	 * Returns the postalcode of this ceg.
	 *
	 * @return the postalcode of this ceg
	 */
	@AutoEscape
	public String getPostalcode();

	/**
	 * Sets the postalcode of this ceg.
	 *
	 * @param postalcode the postalcode of this ceg
	 */
	public void setPostalcode(String postalcode);

	/**
	 * Returns the city of this ceg.
	 *
	 * @return the city of this ceg
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this ceg.
	 *
	 * @param city the city of this ceg
	 */
	public void setCity(String city);

	/**
	 * Returns the street of this ceg.
	 *
	 * @return the street of this ceg
	 */
	@AutoEscape
	public String getStreet();

	/**
	 * Sets the street of this ceg.
	 *
	 * @param street the street of this ceg
	 */
	public void setStreet(String street);

	/**
	 * Returns the contact of this ceg.
	 *
	 * @return the contact of this ceg
	 */
	@AutoEscape
	public String getContact();

	/**
	 * Sets the contact of this ceg.
	 *
	 * @param contact the contact of this ceg
	 */
	public void setContact(String contact);

	/**
	 * Returns the web of this ceg.
	 *
	 * @return the web of this ceg
	 */
	@AutoEscape
	public String getWeb();

	/**
	 * Sets the web of this ceg.
	 *
	 * @param web the web of this ceg
	 */
	public void setWeb(String web);

	/**
	 * Returns the description of this ceg.
	 *
	 * @return the description of this ceg
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this ceg.
	 *
	 * @param description the description of this ceg
	 */
	public void setDescription(String description);

	/**
	 * Returns the htmldescription of this ceg.
	 *
	 * @return the htmldescription of this ceg
	 */
	@AutoEscape
	public String getHtmldescription();

	/**
	 * Sets the htmldescription of this ceg.
	 *
	 * @param htmldescription the htmldescription of this ceg
	 */
	public void setHtmldescription(String htmldescription);

	/**
	 * Returns the keywords of this ceg.
	 *
	 * @return the keywords of this ceg
	 */
	@AutoEscape
	public String getKeywords();

	/**
	 * Sets the keywords of this ceg.
	 *
	 * @param keywords the keywords of this ceg
	 */
	public void setKeywords(String keywords);

	/**
	 * Returns the page u r l of this ceg.
	 *
	 * @return the page u r l of this ceg
	 */
	@AutoEscape
	public String getPageURL();

	/**
	 * Sets the page u r l of this ceg.
	 *
	 * @param pageURL the page u r l of this ceg
	 */
	public void setPageURL(String pageURL);

	/**
	 * Returns the pagename of this ceg.
	 *
	 * @return the pagename of this ceg
	 */
	@AutoEscape
	public String getPagename();

	/**
	 * Sets the pagename of this ceg.
	 *
	 * @param pagename the pagename of this ceg
	 */
	public void setPagename(String pagename);

	/**
	 * Returns the date of this ceg.
	 *
	 * @return the date of this ceg
	 */
	public Date getDate();

	/**
	 * Sets the date of this ceg.
	 *
	 * @param date the date of this ceg
	 */
	public void setDate(Date date);

	/**
	 * Returns the page u r l azon of this ceg.
	 *
	 * @return the page u r l azon of this ceg
	 */
	@AutoEscape
	public String getPageURLAzon();

	/**
	 * Sets the page u r l azon of this ceg.
	 *
	 * @param pageURLAzon the page u r l azon of this ceg
	 */
	public void setPageURLAzon(String pageURLAzon);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Ceg ceg);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Ceg> toCacheModel();

	@Override
	public Ceg toEscapedModel();

	@Override
	public Ceg toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}