/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package dinet.orgsetup62.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Org service. Represents a row in the &quot;orgsetup_Org&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link dinet.orgsetup62.model.impl.OrgModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link dinet.orgsetup62.model.impl.OrgImpl}.
 * </p>
 *
 * @author gyengelaszlo
 * @see Org
 * @see dinet.orgsetup62.model.impl.OrgImpl
 * @see dinet.orgsetup62.model.impl.OrgModelImpl
 * @generated
 */
public interface OrgModel extends BaseModel<Org> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a org model instance should use the {@link Org} interface instead.
	 */

	/**
	 * Returns the primary key of this org.
	 *
	 * @return the primary key of this org
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this org.
	 *
	 * @param primaryKey the primary key of this org
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the org i d of this org.
	 *
	 * @return the org i d of this org
	 */
	public long getOrgID();

	/**
	 * Sets the org i d of this org.
	 *
	 * @param orgID the org i d of this org
	 */
	public void setOrgID(long orgID);

	/**
	 * Returns the orig azon of this org.
	 *
	 * @return the orig azon of this org
	 */
	public long getOrigAzon();

	/**
	 * Sets the orig azon of this org.
	 *
	 * @param origAzon the orig azon of this org
	 */
	public void setOrigAzon(long origAzon);

	/**
	 * Returns the azon_r of this org.
	 *
	 * @return the azon_r of this org
	 */
	public long getAzon_r();

	/**
	 * Sets the azon_r of this org.
	 *
	 * @param azon_r the azon_r of this org
	 */
	public void setAzon_r(long azon_r);

	/**
	 * Returns the sub azon_r of this org.
	 *
	 * @return the sub azon_r of this org
	 */
	public long getSubAzon_r();

	/**
	 * Sets the sub azon_r of this org.
	 *
	 * @param subAzon_r the sub azon_r of this org
	 */
	public void setSubAzon_r(long subAzon_r);

	/**
	 * Returns the category_r of this org.
	 *
	 * @return the category_r of this org
	 */
	@AutoEscape
	public String getCategory_r();

	/**
	 * Sets the category_r of this org.
	 *
	 * @param category_r the category_r of this org
	 */
	public void setCategory_r(String category_r);

	/**
	 * Returns the orgname_r of this org.
	 *
	 * @return the orgname_r of this org
	 */
	@AutoEscape
	public String getOrgname_r();

	/**
	 * Sets the orgname_r of this org.
	 *
	 * @param orgname_r the orgname_r of this org
	 */
	public void setOrgname_r(String orgname_r);

	/**
	 * Returns the city of this org.
	 *
	 * @return the city of this org
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this org.
	 *
	 * @param city the city of this org
	 */
	public void setCity(String city);

	/**
	 * Returns the address1 of this org.
	 *
	 * @return the address1 of this org
	 */
	@AutoEscape
	public String getAddress1();

	/**
	 * Sets the address1 of this org.
	 *
	 * @param address1 the address1 of this org
	 */
	public void setAddress1(String address1);

	/**
	 * Returns the postal code of this org.
	 *
	 * @return the postal code of this org
	 */
	@AutoEscape
	public String getPostalCode();

	/**
	 * Sets the postal code of this org.
	 *
	 * @param postalCode the postal code of this org
	 */
	public void setPostalCode(String postalCode);

	/**
	 * Returns the web u r l of this org.
	 *
	 * @return the web u r l of this org
	 */
	@AutoEscape
	public String getWebURL();

	/**
	 * Sets the web u r l of this org.
	 *
	 * @param webURL the web u r l of this org
	 */
	public void setWebURL(String webURL);

	/**
	 * Returns the contact of this org.
	 *
	 * @return the contact of this org
	 */
	@AutoEscape
	public String getContact();

	/**
	 * Sets the contact of this org.
	 *
	 * @param contact the contact of this org
	 */
	public void setContact(String contact);

	/**
	 * Returns the email address of this org.
	 *
	 * @return the email address of this org
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this org.
	 *
	 * @param emailAddress the email address of this org
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the description of this org.
	 *
	 * @return the description of this org
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this org.
	 *
	 * @param description the description of this org
	 */
	public void setDescription(String description);

	/**
	 * Returns the keywords of this org.
	 *
	 * @return the keywords of this org
	 */
	@AutoEscape
	public String getKeywords();

	/**
	 * Sets the keywords of this org.
	 *
	 * @param keywords the keywords of this org
	 */
	public void setKeywords(String keywords);

	/**
	 * Returns the image u r l of this org.
	 *
	 * @return the image u r l of this org
	 */
	@AutoEscape
	public String getImageURL();

	/**
	 * Sets the image u r l of this org.
	 *
	 * @param imageURL the image u r l of this org
	 */
	public void setImageURL(String imageURL);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Org org);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Org> toCacheModel();

	@Override
	public Org toEscapedModel();

	@Override
	public Org toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}