/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package dinet.orgsetup62.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Product service. Represents a row in the &quot;orgsetup_Product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link dinet.orgsetup62.model.impl.ProductModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link dinet.orgsetup62.model.impl.ProductImpl}.
 * </p>
 *
 * @author gyengelaszlo
 * @see Product
 * @see dinet.orgsetup62.model.impl.ProductImpl
 * @see dinet.orgsetup62.model.impl.ProductModelImpl
 * @generated
 */
public interface ProductModel extends BaseModel<Product> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product model instance should use the {@link Product} interface instead.
	 */

	/**
	 * Returns the primary key of this product.
	 *
	 * @return the primary key of this product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product.
	 *
	 * @param primaryKey the primary key of this product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the azon of this product.
	 *
	 * @return the azon of this product
	 */
	public long getAzon();

	/**
	 * Sets the azon of this product.
	 *
	 * @param azon the azon of this product
	 */
	public void setAzon(long azon);

	/**
	 * Returns the name of this product.
	 *
	 * @return the name of this product
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this product.
	 *
	 * @param name the name of this product
	 */
	public void setName(String name);

	/**
	 * Returns the description of this product.
	 *
	 * @return the description of this product
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this product.
	 *
	 * @param description the description of this product
	 */
	public void setDescription(String description);

	/**
	 * Returns the services of this product.
	 *
	 * @return the services of this product
	 */
	@AutoEscape
	public String getServices();

	/**
	 * Sets the services of this product.
	 *
	 * @param services the services of this product
	 */
	public void setServices(String services);

	/**
	 * Returns the image of this product.
	 *
	 * @return the image of this product
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this product.
	 *
	 * @param image the image of this product
	 */
	public void setImage(String image);

	/**
	 * Returns the datasheet of this product.
	 *
	 * @return the datasheet of this product
	 */
	@AutoEscape
	public String getDatasheet();

	/**
	 * Sets the datasheet of this product.
	 *
	 * @param datasheet the datasheet of this product
	 */
	public void setDatasheet(String datasheet);

	/**
	 * Returns the distributor of this product.
	 *
	 * @return the distributor of this product
	 */
	@AutoEscape
	public String getDistributor();

	/**
	 * Sets the distributor of this product.
	 *
	 * @param distributor the distributor of this product
	 */
	public void setDistributor(String distributor);

	/**
	 * Returns the category of this product.
	 *
	 * @return the category of this product
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this product.
	 *
	 * @param category the category of this product
	 */
	public void setCategory(String category);

	/**
	 * Returns the subcategory of this product.
	 *
	 * @return the subcategory of this product
	 */
	@AutoEscape
	public String getSubcategory();

	/**
	 * Sets the subcategory of this product.
	 *
	 * @param subcategory the subcategory of this product
	 */
	public void setSubcategory(String subcategory);

	/**
	 * Returns the page u r l of this product.
	 *
	 * @return the page u r l of this product
	 */
	@AutoEscape
	public String getPageURL();

	/**
	 * Sets the page u r l of this product.
	 *
	 * @param pageURL the page u r l of this product
	 */
	public void setPageURL(String pageURL);

	/**
	 * Returns the pagetitle of this product.
	 *
	 * @return the pagetitle of this product
	 */
	@AutoEscape
	public String getPagetitle();

	/**
	 * Sets the pagetitle of this product.
	 *
	 * @param pagetitle the pagetitle of this product
	 */
	public void setPagetitle(String pagetitle);

	/**
	 * Returns the startingpage of this product.
	 *
	 * @return the startingpage of this product
	 */
	@AutoEscape
	public String getStartingpage();

	/**
	 * Sets the startingpage of this product.
	 *
	 * @param startingpage the startingpage of this product
	 */
	public void setStartingpage(String startingpage);

	/**
	 * Returns the date of this product.
	 *
	 * @return the date of this product
	 */
	public Date getDate();

	/**
	 * Sets the date of this product.
	 *
	 * @param date the date of this product
	 */
	public void setDate(Date date);

	/**
	 * Returns the liferay org ID of this product.
	 *
	 * @return the liferay org ID of this product
	 */
	public long getLiferayOrgId();

	/**
	 * Sets the liferay org ID of this product.
	 *
	 * @param liferayOrgId the liferay org ID of this product
	 */
	public void setLiferayOrgId(long liferayOrgId);

	/**
	 * Returns the page u r l azon of this product.
	 *
	 * @return the page u r l azon of this product
	 */
	@AutoEscape
	public String getPageURLAzon();

	/**
	 * Sets the page u r l azon of this product.
	 *
	 * @param pageURLAzon the page u r l azon of this product
	 */
	public void setPageURLAzon(String pageURLAzon);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Product product);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Product> toCacheModel();

	@Override
	public Product toEscapedModel();

	@Override
	public Product toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}