/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package dinet.orgsetup62.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import dinet.orgsetup62.model.Foo;

import dinet.orgsetup62.service.FooService;
import dinet.orgsetup62.service.persistence.CegPersistence;
import dinet.orgsetup62.service.persistence.FooPersistence;
import dinet.orgsetup62.service.persistence.OrgPersistence;
import dinet.orgsetup62.service.persistence.ProductPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the foo remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link dinet.orgsetup62.service.impl.FooServiceImpl}.
 * </p>
 *
 * @author gyengelaszlo
 * @see dinet.orgsetup62.service.impl.FooServiceImpl
 * @see dinet.orgsetup62.service.FooServiceUtil
 * @generated
 */
public abstract class FooServiceBaseImpl extends BaseServiceImpl
	implements FooService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link dinet.orgsetup62.service.FooServiceUtil} to access the foo remote service.
	 */

	/**
	 * Returns the ceg local service.
	 *
	 * @return the ceg local service
	 */
	public dinet.orgsetup62.service.CegLocalService getCegLocalService() {
		return cegLocalService;
	}

	/**
	 * Sets the ceg local service.
	 *
	 * @param cegLocalService the ceg local service
	 */
	public void setCegLocalService(
		dinet.orgsetup62.service.CegLocalService cegLocalService) {
		this.cegLocalService = cegLocalService;
	}

	/**
	 * Returns the ceg persistence.
	 *
	 * @return the ceg persistence
	 */
	public CegPersistence getCegPersistence() {
		return cegPersistence;
	}

	/**
	 * Sets the ceg persistence.
	 *
	 * @param cegPersistence the ceg persistence
	 */
	public void setCegPersistence(CegPersistence cegPersistence) {
		this.cegPersistence = cegPersistence;
	}

	/**
	 * Returns the foo local service.
	 *
	 * @return the foo local service
	 */
	public dinet.orgsetup62.service.FooLocalService getFooLocalService() {
		return fooLocalService;
	}

	/**
	 * Sets the foo local service.
	 *
	 * @param fooLocalService the foo local service
	 */
	public void setFooLocalService(
		dinet.orgsetup62.service.FooLocalService fooLocalService) {
		this.fooLocalService = fooLocalService;
	}

	/**
	 * Returns the foo remote service.
	 *
	 * @return the foo remote service
	 */
	public dinet.orgsetup62.service.FooService getFooService() {
		return fooService;
	}

	/**
	 * Sets the foo remote service.
	 *
	 * @param fooService the foo remote service
	 */
	public void setFooService(dinet.orgsetup62.service.FooService fooService) {
		this.fooService = fooService;
	}

	/**
	 * Returns the foo persistence.
	 *
	 * @return the foo persistence
	 */
	public FooPersistence getFooPersistence() {
		return fooPersistence;
	}

	/**
	 * Sets the foo persistence.
	 *
	 * @param fooPersistence the foo persistence
	 */
	public void setFooPersistence(FooPersistence fooPersistence) {
		this.fooPersistence = fooPersistence;
	}

	/**
	 * Returns the org local service.
	 *
	 * @return the org local service
	 */
	public dinet.orgsetup62.service.OrgLocalService getOrgLocalService() {
		return orgLocalService;
	}

	/**
	 * Sets the org local service.
	 *
	 * @param orgLocalService the org local service
	 */
	public void setOrgLocalService(
		dinet.orgsetup62.service.OrgLocalService orgLocalService) {
		this.orgLocalService = orgLocalService;
	}

	/**
	 * Returns the org persistence.
	 *
	 * @return the org persistence
	 */
	public OrgPersistence getOrgPersistence() {
		return orgPersistence;
	}

	/**
	 * Sets the org persistence.
	 *
	 * @param orgPersistence the org persistence
	 */
	public void setOrgPersistence(OrgPersistence orgPersistence) {
		this.orgPersistence = orgPersistence;
	}

	/**
	 * Returns the product local service.
	 *
	 * @return the product local service
	 */
	public dinet.orgsetup62.service.ProductLocalService getProductLocalService() {
		return productLocalService;
	}

	/**
	 * Sets the product local service.
	 *
	 * @param productLocalService the product local service
	 */
	public void setProductLocalService(
		dinet.orgsetup62.service.ProductLocalService productLocalService) {
		this.productLocalService = productLocalService;
	}

	/**
	 * Returns the product persistence.
	 *
	 * @return the product persistence
	 */
	public ProductPersistence getProductPersistence() {
		return productPersistence;
	}

	/**
	 * Sets the product persistence.
	 *
	 * @param productPersistence the product persistence
	 */
	public void setProductPersistence(ProductPersistence productPersistence) {
		this.productPersistence = productPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Foo.class;
	}

	protected String getModelClassName() {
		return Foo.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = fooPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = dinet.orgsetup62.service.CegLocalService.class)
	protected dinet.orgsetup62.service.CegLocalService cegLocalService;
	@BeanReference(type = CegPersistence.class)
	protected CegPersistence cegPersistence;
	@BeanReference(type = dinet.orgsetup62.service.FooLocalService.class)
	protected dinet.orgsetup62.service.FooLocalService fooLocalService;
	@BeanReference(type = dinet.orgsetup62.service.FooService.class)
	protected dinet.orgsetup62.service.FooService fooService;
	@BeanReference(type = FooPersistence.class)
	protected FooPersistence fooPersistence;
	@BeanReference(type = dinet.orgsetup62.service.OrgLocalService.class)
	protected dinet.orgsetup62.service.OrgLocalService orgLocalService;
	@BeanReference(type = OrgPersistence.class)
	protected OrgPersistence orgPersistence;
	@BeanReference(type = dinet.orgsetup62.service.ProductLocalService.class)
	protected dinet.orgsetup62.service.ProductLocalService productLocalService;
	@BeanReference(type = ProductPersistence.class)
	protected ProductPersistence productPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private FooServiceClpInvoker _clpInvoker = new FooServiceClpInvoker();
}